apiVersion: v1
kind: Pod
metadata:
  name: np-pod
  labels:
    app: np-pod
spec:
  containers:
    - name: np-container
      image: 192.168.0.195:5000/nginx:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: np-svc
spec:
  selector:
    app: np-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
