apiVersion: v1

kind: Pod
metadata:
  name: np-pod
  labels:
    app: np-pod
spec:
  containers:
    - name: np-container
      image: rapa.iptime.org:5000/hello

---
apiVersion: v1
kind: Service
metadata:
  name: np-svc
spec:
  selector:
    app: np-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
